### ISSUE TITLE
タイプ別設定→[カラー]タブ→インポート を選択するとハングする

### ISSUE THREAD

**Issue by yuru7** [mocaskr/sakura#1]
以下環境で再現確認しています。

OS : Windows 7 64bit / 10 64bit
Ver : mocaskr_ver 020.20150823-r4027 (Sakura Ver. 2.2.0.1)

**Comment by mocaskr** [comment]
報告ありがとうございます。
手元のソースコードでは修正しました。

v015で入れた強調キーワードを20個にする機能でv017以降で発生します。
(v15-v16でも似たような理由でおかしいはずです)

**Comment by yuru7** [comment]
v21で正常に使えることを確認しました。
早速のご対応、感謝します！
