### ISSUE TITLE
Ctrl+ホイール での拡大縮小が動作しない

### ISSUE THREAD

**Issue by yuru7** [mocaskr/sakura#2]
発生環境は以下のとおりです。
#v022.20160128-r4075 の Fix で手を入れたことが関係している？

OS : Win 10 64bit
SAKURA Ver : v022.20160128-r4075
フォント設定：TTF, OTFフォントいずれでも発生

**Comment by mocaskr** [comment]
報告ありがとうございます。
346f8b7f で || と && が間違ってました
58f9a13e　で修正しました
